### ISSUE TITLE
Grobid returned status code 500

### ISSUE THREAD

**Issue by victor-ab** [allenai/pawls#111]
I followed all the steps to install pawls.

This works: `pawls preprocess pdfplumber skiff_files/apps/pawls/papers`

This don't: `pawls preprocess grobid skiff_files/apps/pawls/papers`
pawls_grobid is running as a service in a separated shell.

```python
$ pawls preprocess grobid skiff_files/apps/pawls/papers
Processing using the grobid preprocessor...
Processing 01E4VGC1YN...:   0%|                                                                                     | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/vuser/anaconda3/bin/pawls", line 33, in <module>
    sys.exit(load_entry_point('pawls==0.0.1', 'console_scripts', 'pawls')())
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/pawls-0.0.1-py3.8.egg/pawls/commands/preprocess.py", line 45, in preprocess
    data = process_grobid(str(path))
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/pawls-0.0.1-py3.8.egg/pawls/preprocessors/grobid.py", line 60, in process_grobid
    grobid_structure = fetch_grobid_structure(pdf_file, grobid_host)
  File "/home/vuser/anaconda3/lib/python3.8/site-packages/pawls-0.0.1-py3.8.egg/pawls/preprocessors/grobid.py", line 17, in fetch_grobid_structure
    raise Exception("Grobid returned status code {}".format(resp.status_code))
Exception: Grobid returned status code 500
```

**Comment by lolipopshock** [comment]
In order to use grobid, I think you need to start the service first by running `docker compose up` in the project's root directory.

**Comment by wpnbos** [comment]
Did you manage to solve this? I'm encountering the same problem.

**Comment by bram49** [comment]
Same problem here. Pdfplumber works, but grobid does not. I have PAWLS running locally in a docker container.
